spring.application.name=project-microservice
spring.datasource.url=jdbc:sqlserver://version-control.database.windows.net:1433;database=project_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=version
spring.datasource.password=Control123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true