spring.application.name=document-microservice
spring.datasource.url=jdbc:sqlserver://version-control.database.windows.net:1433;database=auth_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=version
spring.datasource.password=Control123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true